'use client'
import Navbar from "@/components/Navbar";
import "./globals.css";
import AuthContextProvider from "@/context/AuthContext";
import TweetContextProvider from "@/context/TweetContext";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient()

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
      <QueryClientProvider client={queryClient}>
      <ReactQueryDevtools initialIsOpen={false} />
        <AuthContextProvider>
        <TweetContextProvider>
          <Navbar />
          {children}
        </TweetContextProvider>
        </AuthContextProvider>
      </QueryClientProvider>
      </body>
    </html>
  );
}
